# Generated by Django 5.1.2 on 2025-12-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created'], 'permissions': [('create_post', 'Can add post'), ('edit_post', 'Can change post'), ('remove_post', 'Can delete post')]},
        ),
    ]
