# Generated by Django 6.0.5 on 2026-07-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Portfolio Image'),
        ),
    ]
