# Generated by Django 5.1 on 2024-10-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_options_member_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_contributor',
        ),
    ]
